name: nb_utils
description: Collection of Widgets and helpful Methods that every developer needs.
version: 5.0.0
#homepage: https://bhoominn.github.io
repository: https://github.com/bhoominn/nb_utils
issue_tracker: https://github.com/bhoominn/nb_utils/issues
funding:
  - https://www.github.com/sponsors/bhoominn

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.2
  connectivity_plus: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.nb.nb_utils
        pluginClass: NbUtilsPlugin
      ios:
        pluginClass: NbUtilsPlugin
      linux:
        pluginClass: nb_utils_plugin
      macos:
        pluginClass: NbUtilsPlugin
      windows:
        pluginClass: NbUtilsPlugin

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400